### PR TITLE
Introduce static code analysis

### PR DESCRIPTION
**Pull request by mhmxs**
Golangci-lint, Gosec, Govulncheck and Nilaway has been introduced. CodeQL Github also has been added.

Fixes: https://github.com/linode/cluster-api-provider-linode/issues/44

### CODE REVIEW

**Comment by mhmxs** [comment]
@luthermonson @avestuk @zliang-akamai Could you please take a look

**Review by avestuk — COMMENTED** [review]
I'm fine with the SCA change. I'm glad to see the updates to break out reconcile into smaller pieces!

My one question is why you've chosen to use named returns in all of the the new reconcile functions such as reconcileUpdate. Personally I'm just not used to seeing naked returns in Go and I find it a bit jarring.

**Comment by mhmxs** [comment]
> why you've chosen to use named returns in all of the the new reconcile functions

@avestuk the answer is simply because the original `Reconcilie` function is full of defer statements, and i didn't change the code style during refactoring.

**Comment by avestuk** [comment]
> @avestuk the answer is simply because the original Reconcilie function is full of defer statements, and i didn't change the code style during refactoring.

Eminently reasonable! What do you think about only doing named returns in `Reconcile/reconcile` functions where we have got the defer statements? I'm thinking that it'd be preferable to keep the named return pieces limited to places where we need them in order to modify the return values. That way it's clear why it's being done and we don't have it across the whole code base?

**Comment by mhmxs** [comment]
> That way it's clear why it's being done and we don't have it across the whole code base?

@avestuk I did what i could, but reconcile update has to be an exception too.

**Comment by avestuk** [comment]
That works for me!

**Review by luthermonson — APPROVED** [review]

**Review by shanduur — APPROVED** [review]

**Pull request merged**
