### PR TITLE
chore: migrate from kuttl to chainsaw

### PR DESCRIPTION
**Pull request by eddycharly**
Chainsaw was created because kuttl stopped to be actively maintained (it's actually a single maintainer now).

We are also solving most of the kuttl limitations that exist today and wrote a command to automatically migrate from kuttl to chainsaw. It supercharges e2e tests with better logs, config maps assertions, [assertions trees](https://kyverno.io/blog/2023/12/13/kyverno-chainsaw-exploring-the-power-of-assertion-trees/) and many more things 💪

This is a relatively young project but it has already been adopted by a couple of e2e tests heavy projects (kyverno, keptn, fairwinds rbac-manager, grafana-operator, redis-operator and others).

To give more context, you can see similar PRs at:
- https://github.com/keptn/lifecycle-toolkit/pull/3000
- https://github.com/open-telemetry/opentelemetry-operator/pull/2630
- https://github.com/operator-framework/operator-sdk/pull/6676
- https://github.com/grafana/tempo-operator/pull/786 in this PR the tempo-operator maintainers asked some good questions and I explained the current status, that I suggest taking a look at.

Sadly, [kuttl](https://github.com/kudobuilder/kuttl) haven't done a release since jan 2023.

Here you can find a good video showcasing chainsaw: https://www.youtube.com/watch?v=Ejof-wtAdQM&ab_channel=CamilaMacedo

If you need more infos :point_down:
- GitHub: https://github.com/kyverno/chainsaw
- Docs: https://kyverno.github.io/chainsaw
- Slack: https://kubernetes.slack.com/archives/C067LUFL43U

### CODE REVIEW

**Comment by eddycharly** [comment]
This kuttl-in-kuttl thing... first time i see that 🙈

**Comment by eljohnson92** [comment]
Please open an issue describing what this PR solves

**Comment by eddycharly** [comment]
@eljohnson92 i will do, let me at least update the pr description :)

**Comment by AshleyDumaine** [comment]
Looks like this closes #103 (removing kuttl-in-kuttl)

**Comment by eddycharly** [comment]
@AshleyDumaine yes it could fix that (and more)

**Comment by eljohnson92** [comment]
@eddycharly we have done a pretty major refactor of our kuttl testing including removing the kuttl-in-kuttl and complications in the byoc. I suspect a migration path to chainsaw would now be much simpler. is there any tooling around transitioning from kuttl to chainsaw?

**Comment by eddycharly** [comment]
You can use `chainsaw migrate kuttl tests ...` to convert them automatically. It's not 100% reliable though.

I think the only test that is not easy to migrate to chainsaw yet is the `byovpc` one, i will investigate next week, it sounds like a good use case.

Another important point is that you probably don't want to migrate as is, there's a lot of features in chainsaw that will make your tests better. Automatic conversion is not going to do that, it's just going to produce a chainsaw equivalent of your kuttl tests.

**Comment by eljohnson92** [comment]
It seems like one of the main usecases we still have to farm out to a Makefile right now is when we `curl` the LInode API to validate backend resources are created, is there any built in `chainsaw` functionality to cover this usecase?

**Comment by eddycharly** [comment]
@eljohnson92 nope, you can still do it with curl though.

I'll look at your tests again today, upcoming v0.1.8 could solve the byovpc issues.

**Comment by eddycharly** [comment]
@eljohnson92 i started over in https://github.com/linode/cluster-api-provider-linode/pull/162

Can you let the workflow run ?

**Pull request closed without merging**
