### PR TITLE
[fix] finalizers to not contain the apiVersion

### PR DESCRIPTION
**Pull request by AshleyDumaine**
**What this PR does / why we need it**: This changes the finalizers to not have the api version in the finalizer string in line with other CAPI providers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by rahulait** [comment]
Changes look good to me. I can approve once the go-analyze tests are fixed and PR is rebased.

**Review by rahulait — APPROVED** [review]
LGTM

**Comment by eljohnson92** [comment]
will this break any resources with the older finalizers or will it gracefully switch to the new finalizer?

**Comment by AshleyDumaine** [comment]
> will this break any resources with the older finalizers or will it gracefully switch to the new finalizer?

I mention this in the special notes above that this doesn't gracefully cut over in the interest of keeping the code clean, hence the [breaking] tag

**Review by eljohnson92 — APPROVED** [review]

**Comment by rahulait** [comment]
LGTM. Can we reduce the cognitive complexity or skip it so that this check doesn't break on main branch?

**Review by eljohnson92 — APPROVED** [review]

**Pull request merged**
